daily_fresh/daily_fresh/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('df_goods.urls', namespace='df_goods')),
    url(r'^admin/', admin.site.urls),
    url(r'^df_user/', include('df_user.urls', namespace='df_user')),
    # url(r'^df_goods/', include('df_goods.urls', namespace='df_goods')),
    url(r'^df_cart/', include('df_cart.urls', namespace='df_cart')),
    url(r'^df_order/', include('df_order.urls', namespace='df_order')),
    url(r'^tinymce/', include('tinymce.urls', namespace='tinymce')),
    url('^search/', include('haystack.urls', namespace='haystack')),
    url(r'df_celery/', include('df_celery.urls', namespace='df_celery')),

]

daily_fresh/df_cart/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^cart_add/(\d+)/(\d+)/$', views.cart_add, name='cart_add'),
    url(r'^cart_delete/(\d+)/$', views.cart_delete, name='cart_delete'),
    url(r'^cart_count/$', views.cart_count, name='cart_count'),
    url(r'^cart_edit_count/(\d+)/(\d+)/$', views.cart_edit_count, name='cart_edit_count'),
    url(r'^cart_edit_status/(\d+)/(\d+)/$', views.cart_edit_status, name='cart_edit_status'),
    # url(r'^cart_edit_status/$', views.cart_edit_status, name='cart_edit_status'),
]

daily_fresh/df_goods/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index/$', views.index, name='index'),
    url(r'^list/(\d+)/(\w+)/(\d+)/$', views.list, name='list'),
    url(r'^detail/(\d+)/$', views.detail, name='detail'),
]

daily_fresh/df_user/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^register/$', views.register, name='register'),
    url(r'^register_exist/$', views.register_exist, name='register_exist'),
    url(r'^register_handle/$', views.register_handle, name='register_handle'),
    url(r'^login/$', views.login, name='login'),
    url(r'^login_haddle/$', views.login_handle, name='login_haddle'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^user_center_info/$', views.user_center_info, name='user_center_info'),
    url(r'^user_center_order/(\d+)/$', views.user_center_order, name='user_center_order'),
    url(r'^user_center_site/$', views.user_center_site, name='user_center_site'),
    url(r'^site_haddle/$', views.site_haddle, name='site_haddle')

]

daily_fresh/df_order/models.py
from django.db import models

class OrderInfo(models.Model):
    odate = models.DateField(auto_now=True)
    user = models.ForeignKey('df_user.UserInfo')
    ototle = models.DecimalField(max_digits=6, decimal_places=2)
    oaddress = models.CharField(max_length=150)
    is_pay = models.BooleanField(default=False)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return self.user.uname+':'+str(self.id)


class OrderDetailInfo(models.Model):
    goods = models.ForeignKey('df_goods.GoodsInfo')
    ocount = models.IntegerField()
    order = models.ForeignKey(OrderInfo)

    class Meta:
        ordering = ['order_id']

    def __str__(self):
        return self.goods.gtitle + '-' + str(self.ocount) + ':' + self.order_id

daily_fresh/df_user/models.py
from django.db import models


class UserInfo(models.Model):
    uname = models.CharField(max_length=20)
    upwd = models.CharField(max_length=40)
    uemail = models.CharField(max_length=30)
    uaddress = models.CharField(max_length=100, default='', null=True, blank=True)
    uphone = models.CharField(max_length=11, default='', null=True, blank=True)

    # default blank是python层面的约束，不影响数据库结构
    # null是数据库层面的约束，会影响数据库结构

    class Meta:
        ordering = ['pk', 'uname']

    def __str__(self):
        return self.uname

class SiteInfo(models.Model):
    '''收货地址类'''
    sperson = models.CharField(max_length=20)
    saddress = models.CharField(max_length=100)
    spostcode = models.CharField(max_length=6, default='', null=True)
    sphone = models.CharField(max_length=11)
    is_default = models.BooleanField(default=False)
    user = models.ForeignKey(UserInfo)

    class Meta:
        ordering = ['pk', 'user']

    def __str__(self):
        return self.sperson+'/'+self.saddress+'/'+self.sperson

daily_fresh/df_user/views.py
# -*- coding:utf-8 -*-

from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator
from django.core.cache import cache
from .models import *
from df_order.models import *
from df_goods.models import *
from hashlib import sha1
from functools import wraps
from django.contrib.sessions import base_session


def register(request):
    """
    功能：用户注册页面
    :param request: 默认request参数
    :return: 用户注册页面
    """
    cookie = request.COOKIES
    name = cookie.get('regi_uname', '')
    email = cookie.get('regi_uemail', '')
    context = {'regi_name': name, 'regi_email': email}
    return render(request, 'df_user/register.html', context)


def register_exist(request):
    """
    功能：判断用户名是否存在，处理ajax请求
    :param request: 默认request参数
    :return: JsonResponse对象
    """
    # 获取用户输入的用户名，查询数据库是否存在该用户名
    uname = request.GET.get('regi_name')
    result = UserInfo.objects.filter(uname=uname).exists()
    context = {'result': result}
    return JsonResponse(context)


def register_handle(request):
    """
    功能：用户名注册处理，处理post请求
    :param request: 默认request参数
    :return: 重定向到登录页面或注册页面
    """
    # 获取提交的用户名、密码
    post = request.POST
    uname = post.get('user_name')
    pwd = post.get('pwd')
    # 判断两次密码是否相同、用户名是否存在
    if post.get('pwd') != post.get('cpwd') or UserInfo.objects.filter(uname=uname).exists():
        # 获取重定向页面
        red = redirect(reverse('df_user:register'))
        # 设置COOKIES
        red.set_cookie('regi_name', post.get('user_name'), max_age=300)
        red.set_cookie('regi_email', post.get('email'), max_age=300)
        return red
    else:
        # 使用sha1进行密码加密
        s1 = sha1()
        s1.update(pwd.encode())
        upwd = s1.hexdigest()
        # 创建UserInfo对象，赋值并保存
        user = UserInfo()
        user.uname = uname
        user.upwd = upwd
        user.uemail = post.get('email')
        user.save()
        return redirect(reverse('df_user:login', args=()))


def login(request):
    """
    功能：登录页面
    :param request: 默认request参数
    :return: 登录页面
    """
    # 打印request.META中的键值对内容
    # for item in request.META:
    #     print(item+'======', end='')
    #     print(request.META[item])
    # 尝试获取COOKIES中保存的uname，如果以前登录并记录过用户名，则直接显示用户名
    uname = request.COOKIES.get('uname', '')
    context = {'uname': uname, 'error_name': 0, 'error_pwd': 0}
    return render(request, 'df_user/login.html', context)


def login_handle(request):
    """
    功能：登陆处理
    :param request: 默认request参数
    :return:
    """
    # 获取POST属性
    post = request.POST
    # 获取post中的value值
    uname = post.get('user_name')
    upwd = post.get('pwd')
    remember = post.get('remember', '0')
    # 获取uname的查询集
    users = UserInfo.objects.filter(uname=uname)
    # 判断用户名是否存在
    if bool(users):
        # 密码加密处理
        s = sha1()
        s.update(upwd.encode())
        upwd_sha = s.hexdigest()
        # 判断密码是否正确
        if upwd_sha == users[0].upwd:
            # 尝试获取跳转前的原页面url(未登录状态下点击添加购物车)
            if 'HTTP_REFERER' in request.COOKIES:
                url = request.COOKIES.get('HTTP_REFERER')
            # 若无法获取到原页面url，则尝试获取跳转前想要请求的页面，default值设置为首页url
            else:
                url = request.COOKIES.get('request_url', reverse('df_goods:index'))
            # 构造HttpResponseRedirect对象
            red = redirect(url)
            # 删除COOKIES['HTTP_REFERER']中保存的跳转前的原页面地址、跳转前想要请求的地址
            red.delete_cookie('HTTP_REFERER')
            red.delete_cookie('request_url')

            # 设置cookie，记住用户名
            if remember == '1':
                red.set_cookie('uname', uname)
            else:
                red.set_cookie('uname', '', max_age=-1)
            # 设置session内容及过期时间(可在setting文件中配置)，状态保持
            request.session['user'] = users[0]
            request.session['user_id'] = users[0].id
            request.session['uname'] = uname
            # request.session.set_expiry(7200)
            return red
        else:
            # 构造HttpResponseRedirect对象
            red = redirect(reverse('df_user:login'))
            # 设置cookie，记住用户名
            if remember == '1':
                red.set_cookie('uname', uname)
            else:
                red.set_cookie('uname', '', max_age=-1)
            red.set_cookie('error_name', 0)
            red.set_cookie('error_pwd', 1)
            return red
    else:
        # 构造HttpResponseRedirect对象
        red = redirect(reverse('df_user:login'))
        # 设置cookie，记住用户名
        if remember == '1':
            red.set_cookie('uname', uname)
        else:
            red.set_cookie('uname', '', max_age=-1)
        red.set_cookie('error_name', 1)
        red.set_cookie('error_pwd', 0)
        return red


def authenticated(func):
    """
    功能：装饰器，用户登录状态认证
    :param func:
    :return:
    """
    @wraps(func)
    def inner_func(request, *args, **kwargs):
        """
        功能：扩充后的新函数
        :param request: 原函数的默认参数
        :param args: 原函数的位置参数，采用不定长参数形式来表示
        :param kwargs: 原函数的关键字参数，采用不定长参数形式来表示
        :return:
        """
        # 若已登录则继续执行原视图
        if request.session.get('user_id'):
            return func(request, *args, **kwargs)
        # 若未登录，则重定向到登录页面
        else:
            redi = redirect(reverse('df_user:login'))
            # 设置cookie保存原来的页面地址
            redi.set_cookie('request_url', request.get_full_path())
            return redi
    return inner_func


def logout(request):
    """
    功能：删除session，退出登录，重定向到首页
    :param request: 默认request参数
    :return: 首页
    """
    # 删除session
    request.session.flush()
    # 获取重定向页面
    resp = redirect(reverse('df_goods:index'))
    # 删除COOKIES中记录购物车商品数量的键：count
    resp.delete_cookie('count')
    return resp


@authenticated
def user_center_info(request):
    """
    功能：用户中心页面
    :param request: 默认request参数
    :return: 用户中心页面
    """
    # 根据session保存的user_id获取user对象,以及相关信息
    user = request.session.get('user')
    # 获取最近浏览商品id列表
    id_list_str = request.COOKIES.get('browsed_goods_id_list')
    id_list = []
    goods_list = []
    if id_list_str:
        id_list = id_list_str.split(',')
    for id in id_list:
        goods_list.append(GoodsInfo.objects.get(pk=id))
    # 构造Json数据
    context = {
        'font_flag': 'user_center',
        'uname': user.uname,
        'uemail': user.uemail,
        'uphone': user.uphone,
        'uaddress': user.uaddress,
        'goods_list': goods_list,
    }
    return render(request, 'df_user/user_center_info.html', context)


@authenticated
def user_center_order(request, index):
    """
    功能：用户中心---订单列表页面
    :param request: 默认request参数
    :param index: 订单页页码
    :return: 订单列表页面
    """
    # 获取用户id；并尝试从缓存中获取Paginator对象
    user_id = request.session['user_id']
    paginator = cache.get('order_list_paginator:'+str(user_id))
    # 如果缓存中没有（即返回None），则查询数据库；对QuerySet分页；并将Paginator对象缓存至数据库；
    if not paginator:
        order_list = OrderInfo.objects.filter(user_id=user_id, is_pay=False).order_by('-pk')
        paginator = Paginator(order_list, 8)
        cache.set('order_list_paginator:'+str(user_id), paginator, 60*5)
    # 获取请求的页；构造模板上下文；返回结果
    page = paginator.page(int(index))
    context = {'font_flag': 'user_center', 'page': page}
    return render(request, 'df_user/user_center_order.html', context)


def site_haddle(request):
    """
    功能：添加收货地址
    :param request: 默认request参数
    :return:
    """
    post = request.POST
    site = SiteInfo()
    site.sperson = post.get('sperson')
    site.sphone = post.get('sphone')
    site.spostcode = post.get('spostcode')
    site.saddress = post.get('saddress')
    # 外键user的值必须是一个UserInfo对象，可直接使用user_id进行赋值操作
    site.user_id = request.session['user_id']
    site.save()
    return redirect(reverse('df_user:user_center_site'))


@authenticated
def user_center_site(request):
    """
    功能：用户中心---收货地址页面
    :param request: 默认request参数
    :return: 用户中心---收货地址页面
    """
    # 获取用户默认收货地址
    # 外键user的值必须是一个UserInfo对象，可直接使用user_id进行查询操作
    sites = SiteInfo.objects.filter(user_id=request.session['user_id'], is_default=True)
    site = sites[0]
    # 构建Json数据
    context = {
        'font_flag': 'user_center',
        'sperson': site.sperson,
        'sphone': site.sphone,
        'saddress': site.saddress,
        'spostcode': site.spostcode,
    }
    return render(request, 'df_user/user_center_site.html', context)

daily_fresh/templates/df_user/base_top.html
{% extends 'df_user/base_footer.html' %}


{% block base_head %}
    <script>
        {# 获取购物车商品数量，并在购物车图标处显示 #}
        $(function () {
            var url = '{% url 'df_cart:cart_count' %}';
            $.get(url, function (data) {
                $('#show_count').text(data.count);
            });
        })
    </script>

    {% block head %}

    {% endblock %}
{% endblock base_head %}


{% block body%}
    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_btn fl">
                    <a href="{% url 'df_goods:index' %}">首页</a>
                    <span>|</span>
                    {% if request.session.uname|default:'' == '' %}
                        <a href="{% url 'df_user:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'df_user:register' %}">注册</a>
                    {% else %}
                        欢迎您：<em>{{ request.session.uname }}</em>
                        <span>|</span>
                        <a href="{% url 'df_user:logout' %}">退出</a>
                    {% endif %}
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'df_user:user_center_info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'df_cart:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'df_user:user_center_order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>

    <div class="search_bar clearfix">
        <a href="{% url 'df_goods:index' %}" class="logo fl"><img src="/static/daily_fresh/images/logo.png"></a>

        {% if font_flag != 'goods' %}
            <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;
                {% if font_flag == 'user_center' %}
                    用户中心
                {% endif %}
                {% if font_flag == 'cart' %}
                    购物车
                {% endif %}
                {% if font_flag == 'place_order' %}
                    提交订单
                {% endif %}
            </div>

            <div class="search_con fr">
                <form action="/search/" method="get" target="_blank">
                    <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                    <input type="button" class="input_btn fr" value="搜索">
                </form>
            </div>
        {% else %}
            <div class="search_con fl">
                <form action="/search/" method="get" target="_blank">
                    <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                    <input type="button" class="input_btn fr" value="搜索">
                </form>
		    </div>
            <div class="guest_cart fr">
                <a href="{% url 'df_cart:cart' %}" class="cart_name fl">我的购物车</a>
                <div class="goods_count fl" id="show_count"></div>
            </div>
        {% endif %}
    </div>

    {% block center %}

    {% endblock %}
{% endblock body%}

daily_fresh/templates/df_user/login.html
{% extends 'df_user/base_footer.html' %}


{% block base_head %}
    <script>
        $(function () {
            !function () {
                var error_name = $.cookie('error_name');
                var error_pwd = $.cookie('error_pwd');
                if(error_name === '1'){
                    $('.user_error').text('用户名错误！').show();
                    $('.pwd_error').hide();
                    $.cookie('error_name', null, {expires:-1, path: '/'});
                    $.cookie('error_pwd', null, {expires: -1, path: '/'});
                }

                if(error_pwd === '1'){
                    $('.user_error').hide();
                    $('.pwd_error').text('密码错误！').show();
                    $.cookie('error_name', null, {expires:-1, path: '/'});
                    $.cookie('error_pwd', null, {expires: -1, path: '/'});
                }
            }();

            {# 记住密码 #}
            $('#remember').click(function () {
                if($(this).prop('checked')){
                    $(this).val('1');
                }else {
                    $(this).val('0');
                }
            });
        });
    </script>
{% endblock base_head %}


{% block title %}
    天天生鲜-登录
{% endblock %}


{% block body %}

	<div class="login_top clearfix">
		<a href="{% url 'df_goods:index' %}" class="login_logo"><img src="/static/daily_fresh/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'df_user:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post" action="{% url 'df_user:login_haddle' %}">

                        {% csrf_token %}

						<input type="text" name="user_name" class="name_input" value="{{ uname }}" placeholder="请输入用户名">
						<div class="user_error">用户名错误</div>

						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">密码错误</div>

						<div class="more_input clearfix">
							<input type="checkbox" id="remember" name="remember" value="1" checked="checked">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>

						<input type="submit" name="" value="登录" class="input_submit">

					</form>
				</div>
			</div>
		</div>
	</div>

{% endblock body %}

daily_fresh/templates/df_user/register.html
{% extends 'df_user/base_footer.html' %}


{% block title %}
    用户注册
{% endblock %}


{% block base_head %}
    <script type="text/javascript" src="/static/daily_fresh/js/register.js"></script>
{% endblock base_head %}


{% block body %}

<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/daily_fresh/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'df_user:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="{% url 'df_user:register_handle' %}" method="post">
                    {% csrf_token %}
                    <ul>
                        <li>
                            <label>用户名:</label>
                            <input type="text" name="user_name" value="{{ request.COOKIES.regi_name }}" id="user_name">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>密码:</label>
                            <input type="password" name="pwd" id="pwd">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>确认密码:</label>
                            <input type="password" name="cpwd" id="cpwd">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>邮箱:</label>
                            <input type="text" name="email" value="{{ request.COOKIES.regi_email }}" id="email">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li class="agreement">
                            <input type="checkbox" name="allow" id="allow" checked="checked">
                            <label>同意”天天生鲜用户使用协议“</label>
                            <span class="error_tip2">提示信息</span>
                        </li>
                        <li class="reg_sub">
                            <input type="submit" value="注 册" name="">
                        </li>
                    </ul>
				</form>
			</div>

		</div>

	</div>

{% endblock body%}


daily_fresh/templates/df_user/user_center_info.html
{% extends 'df_user/base_top.html' %}

{% block title %}
    天天生鲜-用户中心
{% endblock title %}


{% block center %}

    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'df_user:user_center_info' %}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'df_user:user_center_order' 1 %}">· 全部订单</a></li>
				<li><a href="{% url 'df_user:user_center_site' %}">· 收货地址</a></li>
			</ul>
		</div>

        <div class="right_content clearfix">
            <div class="info_con clearfix">
                <h3 class="common_title2">基本信息</h3>
                    <ul class="user_info_list">
                        <li><span>用户名：</span>{{ uname }}</li>
                        <li><span>邮箱地址：</span>{{ uemail }}</li>
                        <li><span>联系方式：</span>{{ uphone }}</li>
                        <li><span>联系地址：</span>{{ uaddress }}</li>
                    </ul>
            </div>

            <h3 class="common_title2">最近浏览</h3>
                <div class="has_view_list">
                <ul class="goods_type_list clearfix">

                    {% for goods in goods_list %}
                        <li>
                            <a href="{% url 'df_goods:detail' goods.pk %}"><img src="/static/media/{{ goods.gpic }}"></a>
                            <h4><a href="{% url 'df_goods:detail' goods.pk %}">{{ goods.gtitle }}</a></h4>
                            <div class="operate">
                                <span class="prize">￥{{ goods.gprice }}</span>
                                <span class="unit">{{ goods.gprice }}/{{ goods.gunit }}</span>
                                <a href="#" class="add_goods" title="加入购物车"></a>
                            </div>
                        </li>
                    {% endfor %}

                </ul>
            </div>
        </div>
    </div>

{% endblock center %}

daily_fresh/templates/df_user/user_center_order.html
{% extends 'df_user/base_top.html' %}

{% block title %}
    天天生鲜-用户中心
{% endblock title %}

{% block head %}
    <script>
        $(function () {
            $('.subtotle').each(function () {
                var price = $(this).siblings('.col05').children('.price').text();
                var count = $(this).prev().text();
                var subtotle= parseFloat(price)*parseInt(count);
                $(this).text(subtotle.toFixed(2)+'元');
            })
        })
    </script>
{% endblock %}

{% block center %}

    <div class="main_con clearfix">
        {# 左侧用户中心选项按钮 #}
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'df_user:user_center_info' %}">· 个人信息</a></li>
				<li><a href="{% url 'df_user:user_center_order' 1 %}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'df_user:user_center_site' %}">· 收货地址</a></li>
			</ul>
		</div>
        {# 右侧订单信息 #}
        <div class="right_content clearfix">
            <h3 class="common_title2">全部订单</h3>
            {# 订单列表 #}
            {% for order in page %}
                <ul class="order_list_th w978 clearfix">
                    <li class="col01">{{ order.odate }}</li>
                    <li class="col02">订单号：<em>{{ order.pk }}</em></li>
                    <li class="col02 stress">未支付</li>
                </ul>
                {# 订单内的商品 #}
                <table class="order_list_table w980">
                        <tr>
                            <td width="55%">
                                {% for detail in order.orderdetailinfo_set.all %}
                                <ul class="order_goods_list clearfix">
                                    <li class="col01">
                                        <a href="{% url 'df_goods:detail' detail.goods_id %}">
                                            <img src="/static/media/{{ detail.goods.gpic }}">
                                        </a>
                                    </li>
                                    <li class="col02">
                                        <a href="{% url 'df_goods:detail' detail.goods_id %}">
                                            {{ detail.goods.gtitle }}
                                        </a>
                                    </li>
                                    <li class="col05">
                                        <em class="price">{{ detail.goods.gprice }}元</em>/{{ detail.goods.gunit }}
                                    </li>
                                    <li class="col03">{{ detail.ocount }}</li>
                                    <li class="col04 subtotle"></li>
                                </ul>
                                {% endfor %}
                            </td>
                            <td width="15%" class="totle">{{ order.ototle }}元</td>
                            <td width="15%">待付款</td>
                            <td width="15%"><a href="javascript:;" class="oper_btn">去付款</a></td>
                        </tr>
                </table>
            {% endfor %}

            {# 底部分页按钮 #}
            <div class="pagenation">
                {% if page.has_previous %}
                    <a href="{% url 'df_user:user_center_order' page.previous_page_number %}">< 上一页</a>
                {% else %}
                    <a href="javascript:;">< 上一页</a>
                {% endif %}
                {% for index in page.paginator.page_range %}
                    {% if page.number == index %}
                        <a href="javascript:;" class="active">{{ index }}</a>
                    {% else %}
                        <a href="{% url 'df_user:user_center_order' index %}" class="active">{{ index }}</a>
                    {% endif %}
                {% endfor %}
                {% if page.has_next %}
                    <a href="{% url 'df_user:user_center_order' page.next_page_number %}">下一页 ></a>
                {% else %}
                    <a href="javascript:;">下一页 ></a>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock center %}

daily_fresh/templates/df_user/user_center_site.html
{% extends 'df_user/base_top.html' %}


{% block title %}
    天天生鲜-用户中心
{% endblock title %}


{% block center %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'df_user:user_center_info' %}">· 个人信息</a></li>
				<li><a href="{% url 'df_user:user_center_order' 1 %}">· 全部订单</a></li>
				<li><a href="{% url 'df_user:user_center_site' %}" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{ saddress }} &nbsp&nbsp&nbsp ({{ sperson }}) &nbsp&nbsp{{ sphone }}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="{% url 'df_user:site_haddle' %}" method="post">

						{% csrf_token %}

						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="sperson">
						</div>

						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="saddress"></textarea>
						</div>

						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="spostcode">
						</div>

						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="sphone">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>

{% endblock center %}