daily_fresh/daily_fresh/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('df_goods.urls', namespace='df_goods')),
    url(r'^admin/', admin.site.urls),
    url(r'^df_user/', include('df_user.urls', namespace='df_user')),
    # url(r'^df_goods/', include('df_goods.urls', namespace='df_goods')),
    url(r'^df_cart/', include('df_cart.urls', namespace='df_cart')),
    url(r'^df_order/', include('df_order.urls', namespace='df_order')),
    url(r'^tinymce/', include('tinymce.urls', namespace='tinymce')),
    url('^search/', include('haystack.urls', namespace='haystack')),
    url(r'df_celery/', include('df_celery.urls', namespace='df_celery')),

]

daily_fresh/df_cart/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^cart_add/(\d+)/(\d+)/$', views.cart_add, name='cart_add'),
    url(r'^cart_delete/(\d+)/$', views.cart_delete, name='cart_delete'),
    url(r'^cart_count/$', views.cart_count, name='cart_count'),
    url(r'^cart_edit_count/(\d+)/(\d+)/$', views.cart_edit_count, name='cart_edit_count'),
    url(r'^cart_edit_status/(\d+)/(\d+)/$', views.cart_edit_status, name='cart_edit_status'),
    # url(r'^cart_edit_status/$', views.cart_edit_status, name='cart_edit_status'),
]

daily_fresh/df_order/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^place_order/$', views.place_order, name='place_order'),
    url(r'^order_haddle/$', views.order_haddle, name='order_haddle'),
]

daily_fresh/df_user/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^register/$', views.register, name='register'),
    url(r'^register_exist/$', views.register_exist, name='register_exist'),
    url(r'^register_handle/$', views.register_handle, name='register_handle'),
    url(r'^login/$', views.login, name='login'),
    url(r'^login_haddle/$', views.login_handle, name='login_haddle'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^user_center_info/$', views.user_center_info, name='user_center_info'),
    url(r'^user_center_order/(\d+)/$', views.user_center_order, name='user_center_order'),
    url(r'^user_center_site/$', views.user_center_site, name='user_center_site'),
    url(r'^site_haddle/$', views.site_haddle, name='site_haddle')

]

daily_fresh/df_order/models.py
from django.db import models

class OrderInfo(models.Model):
    odate = models.DateField(auto_now=True)
    user = models.ForeignKey('df_user.UserInfo')
    ototle = models.DecimalField(max_digits=6, decimal_places=2)
    oaddress = models.CharField(max_length=150)
    is_pay = models.BooleanField(default=False)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return self.user.uname+':'+str(self.id)


class OrderDetailInfo(models.Model):
    goods = models.ForeignKey('df_goods.GoodsInfo')
    ocount = models.IntegerField()
    order = models.ForeignKey(OrderInfo)

    class Meta:
        ordering = ['order_id']

    def __str__(self):
        return self.goods.gtitle + '-' + str(self.ocount) + ':' + self.order_id

daily_fresh/df_order/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse, JsonResponse
from django.db import transaction
from .models import *
from df_cart.models import *
from df_user.models import *
from df_user.views import authenticated
from datetime import datetime


@authenticated
def place_order(request):
    site = UserInfo.objects.get(id=request.session.get('user_id')).siteinfo_set.get(is_default=True)
    cart_list = CartInfo.objects.filter(is_selected=True)
    length = len(cart_list)
    # 取反速度比排序快，建议用取反
    # index_list.sort(reverse=True)
    index_list = [x for x in range(1, len(cart_list)+1)][::-1]
    context = {
        'font_flag': 'place_order',
        'cart_list': cart_list,
        'index_list': index_list,
        'site': site,
        'length': length,
    }
    return render(request, 'df_order/place_order.html', context)


@transaction.atomic()
def order_haddle(request):
    sid = transaction.savepoint()
    try:
        cart_list = CartInfo.objects.filter(is_selected=True)
        length = len(cart_list)
        user = cart_list[0].user
        totle = 0
        # 判断库存是否足够，计算总价,相应商品库存量扣除
        for cart in cart_list:
            if cart.count < cart.goods.ginventory:
                totle += cart.goods.gprice*cart.count
                cart.goods.ginventory -= cart.count
                cart.goods.save()
            else:
                transaction.savepoint_rollback(sid)
                return JsonResponse({'is_succeed': False, 'inventory': True, 'except': False})
        # 创建订单对象
        order = OrderInfo()
        order.user_id = request.session.get('user_id')
        order.ototle = totle
        order.odate = datetime.now()
        order.oaddress = request.POST.get('address')
        order.save()
        # 创建订单详情对象,并删除购物车商品
        for cart in cart_list:
            order_detail = OrderDetailInfo()
            order_detail.goods = cart.goods
            order_detail.ocount = cart.count
            order_detail.order = order
            order_detail.save()
            cart.delete()
        transaction.savepoint_commit(sid)
        resp = JsonResponse({'is_succeed': True, 'inventory': False, 'except': False})
        resp.set_cookie('count', int(request.COOKIES.get('count'))-length)
        return resp

    except Exception as e:
        print(e)
        transaction.savepoint_rollback(sid)
        return JsonResponse({'is_succeed': False, 'inventory': False, 'except': True})

daily_fresh/templates/df_order/place_order.html
{% extends 'df_user/base_top.html' %}

{% block title %}
    天天生鲜-提交订单
{% endblock title %}


{% block head %}
    <script>
        $(function () {
            !function () {
                var subtotle = 0;
                var totle = 0;
                $('.subtotle').each(function () {
                    var price = $(this).prev().prev().children().text();
                    var count= $(this).prev().text();
                    subtotle = parseFloat(price)*parseInt(count);
                    $(this).text(subtotle.toFixed(2)+'元');
                    totle += subtotle;
                });
                $('#totle_price').text(totle.toFixed(2)+'元');
                $('#totle_pay').text(totle.toFixed(2)+'元');
            }();

            {# 提交订单 #}
            $('#order_btn').click(function() {
                {#localStorage.setItem('order_finish', 2);#}
                var url = '{% url 'df_order:order_haddle' %}';
                var arg = {
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                    'address': $('#site').text(),
                };

                {# 发送POST请求 #}
                $.post(
                    url,
                    arg,
                    function (data) {
                        if(data.is_succeed === true){
                            $('.popup p').text('提交订单成功！');
                            $('.popup_con').fadeIn('fast', function() {
                                setTimeout(function(){
                                    $('.popup_con').fadeOut('fast',function(){
                                        window.location.href = '{% url 'df_user:user_center_order' 1 %}';
                                    });
                                },2000);
                            });
                        }else if(data.inventory === true){
                            $('.popup p').text('抱歉，库存不足！');
                            $('.popup_con').fadeIn('fast', function() {
                                setTimeout(function(){
                                    $('.popup_con').fadeOut('fast',function(){
                                        window.location.href = '{% url 'df_cart:cart' %}';
                                    });
                                },2000);
                            });
                        }else if(data.except){
                            $('.popup p').text('抱歉，发生异常！');
                            $('.popup_con').fadeIn('fast', function() {
                                setTimeout(function(){
                                    $('.popup_con').fadeOut('fast');
                                },2000);
                            });
                        }
                    }
                );
            });
        })
    </script>
    <script type="text/javascript">
    </script>
{% endblock %}


{% block center %}

    <h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
			<dd><input type="radio" name="" checked=""><em id="site">{{ site }}</em></dd>
		</dl>
		<a href="user_center_site.html" class="edit_site">编辑收货地址</a>

	</div>

	<h3 class="common_title">支付方式</h3>
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" checked>
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>

	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>
		</ul>
        {% for cart in cart_list %}
            <ul class="goods_list_td clearfix" id="{{ cart.goods.pk }}">
                <li class="col01">{{ index_list.pop }}</li>
                <li class="col02"><img src="/static/media/{{ cart.goods.gpic }}"></li>
                <li class="col03">{{ cart.goods.gtitle }}</li>
                <li class="col04">{{ cart.goods.gunit }}</li>
                <li class="col05"><em>{{ cart.goods.gprice }}</em>元</li>
                <li class="col06">{{ cart.count }}</li>
                <li class="col07 subtotle"></li>
            </ul>
        {% endfor %}
	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>{{ length }}</em>件商品，总金额<b id="totle_price"></b></div>
			<div class="transit">运费：<b>0元</b></div>
			<div class="total_pay">实付款：<b id="totle_pay"></b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		<a href="javascript:;" id="order_btn">提交订单</a>
	</div>

    <div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>

		<div class="mask"></div>
	</div>

{% endblock %}