daily_fresh/daily_fresh/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('df_goods.urls', namespace='df_goods')),
    url(r'^admin/', admin.site.urls),
    url(r'^df_user/', include('df_user.urls', namespace='df_user')),
    # url(r'^df_goods/', include('df_goods.urls', namespace='df_goods')),
    url(r'^df_cart/', include('df_cart.urls', namespace='df_cart')),
    url(r'^df_order/', include('df_order.urls', namespace='df_order')),
    url(r'^tinymce/', include('tinymce.urls', namespace='tinymce')),
    url('^search/', include('haystack.urls', namespace='haystack')),
    url(r'df_celery/', include('df_celery.urls', namespace='df_celery')),

]

daily_fresh/df_cart/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^cart_add/(\d+)/(\d+)/$', views.cart_add, name='cart_add'),
    url(r'^cart_delete/(\d+)/$', views.cart_delete, name='cart_delete'),
    url(r'^cart_count/$', views.cart_count, name='cart_count'),
    url(r'^cart_edit_count/(\d+)/(\d+)/$', views.cart_edit_count, name='cart_edit_count'),
    url(r'^cart_edit_status/(\d+)/(\d+)/$', views.cart_edit_status, name='cart_edit_status'),
    # url(r'^cart_edit_status/$', views.cart_edit_status, name='cart_edit_status'),
]

daily_fresh/df_goods/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index/$', views.index, name='index'),
    url(r'^list/(\d+)/(\w+)/(\d+)/$', views.list, name='list'),
    url(r'^detail/(\d+)/$', views.detail, name='detail'),
]

daily_fresh/df_user/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^register/$', views.register, name='register'),
    url(r'^register_exist/$', views.register_exist, name='register_exist'),
    url(r'^register_handle/$', views.register_handle, name='register_handle'),
    url(r'^login/$', views.login, name='login'),
    url(r'^login_haddle/$', views.login_handle, name='login_haddle'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^user_center_info/$', views.user_center_info, name='user_center_info'),
    url(r'^user_center_order/(\d+)/$', views.user_center_order, name='user_center_order'),
    url(r'^user_center_site/$', views.user_center_site, name='user_center_site'),
    url(r'^site_haddle/$', views.site_haddle, name='site_haddle')

]

daily_fresh/df_goods/models.py
# -*- coding:utf-8 -*-

from django.db import models
from tinymce.models import HTMLField


class CategoryManager(models.Manager):
    def get_queryset(self):
        return super(CategoryManager, self).get_queryset().filter(is_delete=False)


class GoodsInfoManager(models.Manager):
    def get_queryset(self):
        return super(GoodsInfoManager, self).get_queryset().filter(is_delete=False)


class Category(models.Model):
    """商品分类"""
    ctitle = models.CharField(max_length=20)
    cclass = models.CharField(max_length=20, default='')
    cpic = models.ImageField(upload_to='categorys', null=True, blank=True)
    is_delete = models.BooleanField(default=False)
    # objects = CategoryManager()

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return self.ctitle


class GoodsInfo(models.Model):
    """商品信息类"""
    gtitle = models.CharField(max_length=20)
    gpic = models.ImageField(upload_to='df_goods')
    gprice = models.DecimalField(max_digits=6, decimal_places=2)
    gunit = models.CharField(max_length=10)
    gintro = models.CharField(max_length=100)
    gclick = models.IntegerField()
    gsales = models.IntegerField()
    ginventory = models.IntegerField()
    is_delete = models.BooleanField(default=False)

    category = models.ForeignKey(Category)
    # objects = GoodsInfoManager()

    gdetail = HTMLField(default='')
    # gdetail = models.TextField(max_length=2000)


    class Meta:
        ordering = ['pk']

    def __str__(self):
        return self.gtitle

daily_fresh/df_goods/views.py
# -*- coding:utf-8 -*-

from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_headers, vary_on_cookie
from django.core.cache import cache
from django.db.models import F
from .models import *


# @cache_page(10)
# @vary_on_cookie
def index(request):
    """
    功能：商城主页视图
    :param request: 默认request参数
    :return: 商城主页
    """
    # 获取商品种类查询集
    categorys = Category.objects.filter(is_delete=False)
    # 获取个种类的点击量前四个，以及最新添加的两个，使用insert(0,value)是为了在模板中使用list.pop方法
    list_by_click = []
    list_by_pk = []
    for category in categorys:
        list_by_click.insert(0, category.goodsinfo_set.order_by('-gclick')[0:4])
        list_by_pk.insert(0, category.goodsinfo_set.order_by('-pk')[0:2])
    # 构造模板上下文
    context = {'font_flag': 'goods',
               'categorys': categorys,
               'list_by_click': list_by_click,
               'list_by_pk': list_by_pk,
               }
    return render(request, 'df_goods/index.html', context)


def list(request, cid, type, index):
    """
    功能：天天生鲜具体商品种类的商品列表
    :param request: 默认的request参数
    :param cid: 商品种类id
    :param type: 商品列表排序依据
    :param index: 页码
    :return: 特定种类商品列表页
    """
    # 从缓存获取分类查询集，传递给分类表，如果没有，则查询数据库并缓存
    categorys = cache.get('categorys')
    if not categorys:
        categorys = Category.objects.filter(is_delete=False)
        cache.set('categorys', categorys, 3600)
    # 从缓存获取当前分类中最新的2个商品，如果没有，则查询数据库并缓存结果
    cate00 = cache.get('category_new_goods:'+cid)
    if not cate00:
        category = categorys.get(pk=int(cid))
        cate00 = category.goodsinfo_set.filter(is_delete=False).order_by('-pk')[0:2]
        cache.set('category_new_good:'+cid, cate00, 300)
    # 从缓存中获取当前分类所有商品按制定方式排序的查询集的Paginator分页对象，如果没有，则查询数据库并缓存
    paginator = cache.get('category_goods_list_paginator:'+cid+type)
    if not paginator:
        if type == 'default':
            goods_list = category.goodsinfo_set.filter(is_delete=False).order_by('-gclick')
        elif type == 'price':
            goods_list = category.goodsinfo_set.filter(is_delete=False).order_by('-gprice')
        else:
            goods_list = category.goodsinfo_set.filter(is_delete=False).order_by('-gsales')
        # 查询集分页
        paginator = Paginator(goods_list, 10)
        # 缓存结果
        cache.set('category_goods_list_paginator:'+cid+type, paginator, 300)
    # 获取用户 请求的页
    page = paginator.page(int(index))
    # 构造Json数据
    context = {
        'font_flag': 'goods',
        'categorys': categorys,
        'category': category,
        'type': type,
        'page': page,
        'cate00': cate00
    }
    return render(request, 'df_goods/list.html', context)


def detail(request, gid):
    """
    功能：商品详情页视图
    :param request: 默认request参数
    :param gid: 商品id
    :return: 商品详情页
    """
    # 从缓存获取分类查询集，传递给分类表，如果没有，则查询数据库并缓存
    categorys = cache.get('categorys')
    if not categorys:
        categorys = Category.objects.filter(is_delete=False)
        cache.set('categorys', categorys, 3600)
    # 获取商品对象，维护商品点击量:加1
    goods = cache.get('goods:'+gid)
    if not goods:
        goods = GoodsInfo.objects.get(pk=str(gid))
        cache.set('goods:'+gid, goods, 300)
    # 维护点击量的任务应该交给celery去做，从缓存中得到的goods无法维护点击量
    goods.gclick += 1
    goods.save()
    # 可以使用QuerySet.update()方法结合F对象更改数据库的数值，但是不太实用，直接使用对象更改并save更简洁
    # goods_queryset = GoodsInfo.objects.filter(pk=int(gid))
    # goods_queryset[0].update(gclick=F('gclick')+1)

    # 获取COOKIES,维护最近浏览商品的id
    cookie = request.COOKIES
    browsed_goods_id_list = []
    # 如果COOKIES中存在键：‘browsed_goods_id_list’，则对对应的value切片处理
    if 'browsed_goods_id_list' in cookie:
        browsed_goods_id_list = cookie['browsed_goods_id_list'].split('|')
    # 将商品id写入列表
    try:
        browsed_goods_id_list.remove(gid)
    except Exception:
        pass
    browsed_goods_id_list.insert(0, gid)
    # 若切片所得列表长度是否大于等于5，将最后一个删除
    if len(browsed_goods_id_list) > 5:
        browsed_goods_id_list.pop()

    # 从缓存获取当前分类中最新的2个商品，如果没有，则查询数据库并缓存结果
    category = goods.category
    cid = category.id
    cate00 = cache.get('category_new_goods:'+str(cid))
    if not cate00:
        category = categorys.get(pk=cid)
        cate00 = category.goodsinfo_set.filter(is_delete=False).order_by('-pk')[0:2]
        cache.set('category_new_good:'+str(cid), cate00, 300)
    # 构造模板上下文
    context = {
        'font_flag': 'goods',
        'categorys': categorys,
        'category': category,
        'goods': goods,
        'cate00': cate00
    }
    # 构造渲染页面
    resp = render(request, 'df_goods/detail.html', context)
    # 将商品id列表以'|'为分隔符，组成id字符串,写入COOKIES
    resp.set_cookie('browsed_goods_id_list', '|'.join(browsed_goods_id_list))
    return resp

daily_fresh/templates/df_goods/detail.html
{% extends 'df_user/base_top.html' %}

{% block title %}
    天天生鲜-商品详情
{% endblock %}


{% block head %}

    <script>

        $(function () {

            {# 购买数量+1 #}
            function add() {
                var num = $('#num_show').val();
                num = parseInt(num)+1;
                $('#num_show').val(num);
            }

            {# 购买数量-1 #}
            function minus() {
                var num = $('#num_show').val();
                if(parseInt(num)>1){
                    num = parseInt(num)-1;
                }
                $('#num_show').val(num);
            }

            function calculate_gtotle(){
                var num = $('#num_show').val();
                var totle = parseInt(num)*{{ goods.gprice }};
                $('#gtotle').text(totle.toFixed(2)+'元');
            }


            {# +按钮绑定click事件 #}
            $('#add').click(function () {
                add();
                calculate_gtotle();
            });

            {# - 按钮绑定click事件 #}
            $('#minus').click(function () {
                minus();
                calculate_gtotle();
            });

            {# 加入购物车按钮绑定click事件 #}
            $('#add_cart').click(function () {
                var count = $('#num_show').val();

                {# 在django标签中无法使用jquery变量，只能先用一个字符站位，然后使用replace()方法将占位符替换为jquery变量 #}
                {#var url = "{% url 'df_cart:cart_add' goods.id 0 %}".replace('0',count);#}
                var goods_id = {{ goods.id }};
                url = '/df_cart/cart_add/'+goods_id+'/'+count+'/';

                $.get(url, function (data) {
                    if(data.authenticated){
                        $('#show_count').text(data.cart_count);
                    }else{
                        {#alert('{% url 'df_user:login' %}');#}
                        location.href = '{% url 'df_user:login' %}';
                        {#$(location).attr('href', '{% url 'df_user:login' %}');#}
                    }
                });

            });

        })

    </script>

{% endblock head %}


{% block center %}

   	<div class="navbar_con">
		<div class="navbar clearfix">

            {# 商品分类 #}
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for category in categorys %}
                        <li>
                            <a href="{% url 'df_goods:list' category.pk 'default' 1 %}" class="{{ category.cclass }}">
                                {{ category.ctitle }}
                            </a>
                        </li>
                    {% endfor %}
				</ul>
			</div>

			<ul class="navlist fl">
				<li><a href="{% url 'df_goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

    {# 导航栏 #}
	<div class="breadcrumb">
		<a href="javascript:;">全部分类</a>
		<span>></span>
		<a href="{% url 'df_goods:list' category.pk 'default' 1 %}">{{ category.ctitle }}</a>
		<span>></span>
		<a href="javascript:;">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl">
            <img src="/static/media/{{ goods.gpic }}">
        </div>

        {# 显示商品基本信息 #}
		<div class="goods_detail_list fr">

            {# 名称、简介、价格、单位 #}
			<h3>{{ goods.gtitle }}</h3>
			<p>{{ goods.gintro }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ goods.gprice }}</em></span>
				<span class="show_unit">单  位：{{ goods.gunit }}</span>
			</div>

            {# 数量信息 #}
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" id="num_show" value="1">
					<a href="javascript:;" class="add fr" id="add">+</a>
					<a href="javascript:;" class="minus fr" id="minus">-</a>
				</div>
			</div>

            {# 总价信息、购买按钮、加入购物车按钮 #}
			<div class="total">总价：<em id="gtotle">{{ goods.gprice }}元</em></div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn" id="buy_btn">立即购买</a>
				<a href="javascript:;" class="add_cart" id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">

        {# 商品推荐 #}
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for item in cate00 %}
                        <li>
                            <a href="{% url 'df_goods:detail' item.pk %}"><img src="/static/media/{{ item.gpic }}"></a>
                            <h4><a href="{% url 'df_goods:detail' item.pk %}">{{ item.gtitle }}</a></h4>
                            <div class="prize">￥{{ item.gprice }}</div>
                        </li>
                    {% endfor %}

                </ul>
			</div>
		</div>

        {# 商品介绍、评论 #}
		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ goods.gdetail|safe }}</dd>
				</dl>
			</div>

		</div>
	</div>

    {# 添加购物车动画的圆圈 #}
    <div class="add_jump"></div>

{% endblock %}


{% block script %}

    <script type="text/javascript">
        var $add_x = $('#add_cart').offset().left;
        var $add_y = $('#add_cart').offset().top;

        var $to_x = $('#show_count').offset().left;
        var $to_y = $('#show_count').offset().top;

        $('#add_cart').click(function(){

            $(".add_jump").css({'left':$add_x+80,'top':$add_y+10,'display':'block'})

            $(".add_jump").stop().animate({'left': $to_x+10, 'top': $to_y+9}, "fast", function() {

                $(".add_jump").fadeOut('fast');

                {#$(".add_jump").fadeOut('fast',function(){#}
                {#    $('#show_count').html();#}
               {# });#}
            });
        })
    </script>

{% endblock %}

daily_fresh/templates/df_goods/index.html
{% extends 'df_user/base_top.html' %}


{% block title %}
    天天生鲜-主页
{% endblock title %}


{% block head %}
	<script type="text/javascript" src="/static/daily_fresh/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/daily_fresh/js/slide.js"></script>
{% endblock head %}


{% block center %}

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="{% url 'df_goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">

        {# 商品分类 #}
		<ul class="subnav fl">
            {% for category in categorys %}
                <li>
                    <a href="{% url 'df_goods:list' category.pk 'default' 1 %}" class="{{ category.cclass }}">
                        {{ category.ctitle }}
                    </a>
                </li>
            {% endfor %}
		</ul>

		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/daily_fresh/images/slide.jpg" alt="幻灯片"></li>
				<li><img src="/static/daily_fresh/images/slide02.jpg" alt="幻灯片"></li>
				<li><img src="/static/daily_fresh/images/slide03.jpg" alt="幻灯片"></li>
				<li><img src="/static/daily_fresh/images/slide04.jpg" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="javascript:;"><img src="/static/daily_fresh/images/adv01.jpg"></a>
			<a href="javascript:;"><img src="/static/daily_fresh/images/adv02.jpg"></a>
		</div>
	</div>

    {% for category in categorys %}
        <div class="list_model">
            {# 首页每个分类的两个新品 #}
            <div class="list_title clearfix">
                <h3 class="fl" id="model01">{{ category.ctitle }}</h3>
                <div class="subtitle fl">
                    <span>|</span>
                    {% for goods in list_by_pk.pop %}
                        <a href="#">{{ goods.gtitle }}</a>
                    {% endfor %}
                </div>
                <a href="{% url 'df_goods:list' category.pk 'default' 1 %}" class="goods_more fr" id="fruit_more">
                    查看更多 >
                </a>
            </div>

            {# 首页每个分类的四个点击量靠前的商品 #}
            <div class="goods_con clearfix">
                <div class="goods_banner fl"><img src="/static/media/{{ category.cpic }}"></div>
                <ul class="goods_list fl">
                    {% for goods in list_by_click.pop %}
                        <li>
                            <h4><a href="{% url 'df_goods:detail' goods.pk %}">{{ goods.gtitle }}</a></h4>
                            <a href="{% url 'df_goods:detail' goods.pk %}">
                                <img src="/static/media/{{ goods.gpic }}">
                            </a>
                            <div class="prize">¥ {{ goods.gprice }}</div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endfor %}

{% endblock center %}


{% block script %}

    <script type="text/javascript" src="/static/daily_fresh/js/slide.js"></script>

	<script type="text/javascript">

		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
{% endblock script %}

daily_fresh/templates/df_goods/list.html
{% extends 'df_user/base_top.html' %}

{% block title %}
    天天生鲜-商品列表
{% endblock %}


{% block head %}
    <script>
        $(function () {
            $('.sort_bar').click(function () {
                $(this).addClass('active').siblings().removeClass('active');
            });

            {# 加入购物车 #}
            $('.add_cart').click(function () {
                var gid = $(this).attr('id');
                var url = '/df_cart/cart_add/' + gid + '/1/';
                $.get(url, function (data) {
                    if (data.authenticated) {
                        $('#show_count').text(data.cart_count);
                    }else{
                        location.href = '{% url 'df_user:login' %}';
                    }
                })
            });
        });
    </script>
{% endblock %}


{% block center %}
    <div class="navbar_con">
		<div class="navbar clearfix">

            {# 商品分类 #}
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for item in categorys %}
                        <li>
                            <a href="{% url 'df_goods:list' item.pk 'default' 1 %}" class="{{ item.cclass }}">
                                {{ item.ctitle }}
                            </a>
                        </li>
                    {% endfor %}
				</ul>
			</div>

            <ul class="navlist fl">
				<li><a href="{% url 'df_goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

    {# 页面导航 #}
	<div class="breadcrumb">
		<a href="javascript:;">全部分类</a>
		<span>></span>
		<a href="javascript:;">{{ category.ctitle }}</a>
	</div>

	<div class="main_wrap clearfix">
        {# 商品推荐 #}
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for item in cate00 %}
                        <li>
                            <a href="{% url 'df_goods:detail' item.pk %}"><img src="/static/media/{{ item.gpic }}"></a>
                            <h4><a href="{% url 'df_goods:detail' item.pk %}">{{ item.gtitle }}</a></h4>
                            <div class="prize">￥{{ item.gprice }}</div>
                        </li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			{# 排序按钮 #}
            <div class="sort_bar">
				<a href="{% url 'df_goods:list' category.pk 'default' 1 %}" {% if type == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'df_goods:list' category.pk 'price' 1 %}" {% if type == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'df_goods:list' category.pk 'sales' 1 %}" {% if type == 'sales' %}class="active"{% endif %}>销量</a>
			</div>

            {# 商品列表 #}
			<ul class="goods_type_list clearfix">
                {% for goods in page %}
                    <li>
                        <a href="{% url 'df_goods:detail' goods.pk %}"><img src="/static/media/{{ goods.gpic }}"></a>
                        <h4><a href="{% url 'df_goods:detail' goods.pk %}">{{ goods.gtitle }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ goods.gprice }}</span>
                            <span class="unit">{{ goods.gprice }}/{{ goods.gunit }}</span>
                            <a href="javascript:;" class="add_cart" id="{{ goods.id }}" title="加入购物车"></a>
                        </div>
                    </li>
                {% endfor %}
			</ul>

            {# 底部页码 #}
			<div class="pagenation">
                {% if page.has_previous %}
                    <a href="{% url 'df_goods:list' category.pk type page.number|add:-1 %}">< 上一页</a>
                {% else %}
                    <a href="javascript:;">< 上一页</a>
                {% endif %}

                {% for index in page.paginator.page_range %}
                    {% if page.number == index %}
                        <a href="javascript:;" class="active">{{ index }}</a>
                    {% else %}
                        <a href="{% url 'df_goods:list' category.pk type index %}">{{ index }}</a>
                    {% endif %}
                {% endfor %}

                {% if page.has_next %}
                    <a href="{% url 'df_goods:list' category.pk type page.number|add:1 %}">下一页 ></a>
                {% else %}
                    <a href="javascript:;">下一页 ></a>
                {% endif %}
			</div>
		</div>
	</div>
{% endblock %}