daily_fresh/daily_fresh/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('df_goods.urls', namespace='df_goods')),
    url(r'^admin/', admin.site.urls),
    url(r'^df_user/', include('df_user.urls', namespace='df_user')),
    # url(r'^df_goods/', include('df_goods.urls', namespace='df_goods')),
    url(r'^df_cart/', include('df_cart.urls', namespace='df_cart')),
    url(r'^df_order/', include('df_order.urls', namespace='df_order')),
    url(r'^tinymce/', include('tinymce.urls', namespace='tinymce')),
    url('^search/', include('haystack.urls', namespace='haystack')),
    url(r'df_celery/', include('df_celery.urls', namespace='df_celery')),

]

daily_fresh/df_cart/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^cart_add/(\d+)/(\d+)/$', views.cart_add, name='cart_add'),
    url(r'^cart_delete/(\d+)/$', views.cart_delete, name='cart_delete'),
    url(r'^cart_count/$', views.cart_count, name='cart_count'),
    url(r'^cart_edit_count/(\d+)/(\d+)/$', views.cart_edit_count, name='cart_edit_count'),
    url(r'^cart_edit_status/(\d+)/(\d+)/$', views.cart_edit_status, name='cart_edit_status'),
    # url(r'^cart_edit_status/$', views.cart_edit_status, name='cart_edit_status'),
]

daily_fresh/df_goods/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index/$', views.index, name='index'),
    url(r'^list/(\d+)/(\w+)/(\d+)/$', views.list, name='list'),
    url(r'^detail/(\d+)/$', views.detail, name='detail'),
]

daily_fresh/df_order/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^place_order/$', views.place_order, name='place_order'),
    url(r'^order_haddle/$', views.order_haddle, name='order_haddle'),
]

daily_fresh/df_cart/models.py
from django.db import models
# from df_user.models import *
# from df_goods.models import *


class CartInfo(models.Model):
    # 同一项目中不同app之间，models的外键可以通过导入其它应用的models，
    # 也可以直接以'app_name.ClassName'的方式调用
    user = models.ForeignKey('df_user.UserInfo')
    goods = models.ForeignKey('df_goods.GoodsInfo')
    count = models.IntegerField(default=1)
    is_selected = models.BooleanField(default=False)

    class Meta:
        ordering = ['pk', 'goods']

daily_fresh/df_cart/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse, JsonResponse
from django.db.models import aggregates, F
from django.core.cache import cache

from .models import *
from df_user.views import authenticated


@authenticated
def cart(request):
    """
    功能：购物车页面
    :param request: 默认request参数
    :return: 购物车页面
    """
    # 获取用户id，构建查询集
    user_id = request.session.get('user_id')
    cart_list = CartInfo.objects.filter(user_id=user_id).order_by('-pk')
    # 迫使查询集执行数据库查询，并产生查询集缓存，避免重复执行数据库查询
    bool(cart_list)
    length = len(cart_list)
    context = {'font_flag': 'cart', 'cart_list': cart_list, 'length': length}
    return render(request, 'df_cart/cart.html', context)


def cart_count(request):
    """
    功能：查询购物车商品数量，处理ajax请求
    :param request: 默认request参数
    :return: JsonReponse对象
    """
    user_id = request.session.get('user_id')        # QueryDict对象的get方法的默认返回值为None
    if user_id:
        if 'count' in request.COOKIES:
            count = request.COOKIES['count']
            return JsonResponse({'count': count})
        else:
            count = CartInfo.objects.filter(user_id=int(user_id)).count()
            resp = JsonResponse({'count': count})
            resp.set_cookie('count', count)
            return resp
    else:
        return JsonResponse({'count': 0})


def cart_add(request, gid, count):
    """
    功能：添加商品到购物车
    :param request: 默认request参数
    :param gid: 商品id
    :param count: 商品的数量
    :return: JsonReponse对象
    """
    # 检测用户未登录，设置COOKIES['HTTP_REFERER']，保存request.META['HTTP_REFERER']中的原页面地址
    if not request.session.get('user_id'):
        resp = JsonResponse({'authenticated': False})
        resp.set_cookie('HTTP_REFERER', request.META.get('HTTP_REFERER'))
        return resp
    else:
        # 将获取的参数转化为int类型
        gid = int(gid)
        count = int(count)
        # 获取用户id，
        user_id = int(request.session.get('user_id'))
        # 依据user_id查询用户购物车列表,并求得列表中元素的个数，尝试进一步根据goods_id获取指定cart
        cart_list = CartInfo.objects.filter(user_id=user_id)
        carts = cart_list.filter(goods_id=gid)
        length = len(cart_list)
        # 若商品已存在，则对其count属性进行维护,并返回商品类别的个数
        if bool(carts):
            carts.update(count=F('count')+count)
            return JsonResponse({'authenticated': True, 'cart_count': length})
        else:
            # 若商品不在用户购物车列表中，则新建Cart对象，赋值并保存
            cart = CartInfo(user_id=user_id, goods_id=gid, count=count)
            cart.save()
            # 构造JsonResponse对象，并设置COOKIES
            resp = JsonResponse({'authenticated': True, 'cart_count': length + 1})
            resp.set_cookie('count', length+1)
            return resp


# 购物车商品编辑
def cart_edit_count(request, gid, count):
    user_id = int(request.session['user_id'])
    cart = CartInfo.objects.get(user_id=user_id, goods_id=int(gid))
    cart.count = int(count)
    cart.save()
    return JsonResponse({'is_succeed': True})


# 维护购物车商品是否被选中
def cart_edit_status(request, gid, is_selected):
    user_id = int(request.session['user_id'])
    if gid == '00':
        if is_selected == '1':
            carts = CartInfo.objects.filter(user_id=user_id, is_selected=False)
            for cart in carts:
                cart.is_selected = True
                cart.save()
        else:
            carts = CartInfo.objects.filter(user_id=user_id, is_selected=True)
            for cart in carts:
                cart.is_selected = False
                cart.save()
        return JsonResponse({'is_succeed': True})
    else:
        cart = CartInfo.objects.get(user_id=user_id, goods_id=int(gid))
        if is_selected == '1':
            cart.is_selected = True
        else:
            cart.is_selected = False
        cart.save()
        return JsonResponse({'is_succeed': True})

# def cart_edit_status(request):
#     if request.GET.get('check_all') == 'true':
#         if request.GET.get('status') == 'true':
#             cart_list = CartInfo.objects.filter(is_selected=False)
#             for cart in cart_list:
#                 cart.is_selected = True
#                 cart.save()
#         else:
#             cart_list = CartInfo.objects.filter(is_selected=True)
#             for cart in cart_list:
#                 cart.is_selected = False
#                 cart.save()
#     else:
#         cart = CartInfo.objects.get(goods_id=request.GET.get('goods_id'))
#         if request.GET.get('status') == 'true':
#             cart.is_selected = True
#         else:
#             cart.is_selected = False
#         cart.save()
#     return JsonResponse({})


# 从购物车删除商品
def cart_delete(request, gid):
    user_id = request.session['user_id']
    cart = CartInfo.objects.get(user_id=user_id, goods_id=int(gid))
    cart.delete()
    # count = request.COOKIES['count']
    resp = JsonResponse({'is_delete': True})
    # resp.set_cookie('count', int(count)-1)
    return resp

daily_fresh/templates/df_cart/cart.html
{% extends 'df_user/base_top.html' %}

{% block title %}
    天天生鲜-购物车
{% endblock title %}


{% block head %}
    <script>
        $(function () {
            {# 点击加号，数量加1 #}
            function add(elem){
                var count = elem.prev().val();
                elem.prev().val(parseInt(count)+1);
            }

            {# 点击减号，数量减1 #}
            function minus(elem){
                var count = elem.next().val();
                if(parseInt(count)>1){
                    elem.next().val(parseInt(count)-1);
                }
            }

            {# 计算小计、总价 #}
            function calculate_totle(){
                {# 定义小计、总计变量 #}
                var subtotle = 0;
                var totle = 0;
                {# 计算小计、总结 #}
                $('.col07').each(function () {
                    {# 获取该商品价格、数量，计算小计并填充 #}
                    var price = $(this).siblings('.col05').children('em').text();
                    var count = $(this).prev().children().children('input').val();
                    subtotle = parseFloat(price)*parseInt(count);
                    $(this).text(subtotle.toFixed(2)+'元');
                    {# 计算总价 #}
                    if($(this).siblings('.col01').children('input').prop('checked')){
                        totle += subtotle;
                    }
                });
                {# 填充总价 #}
                $('#totle').text(totle.toFixed(2));
            }

             {# 检验用户输入是否是大于0的数字,若不是，默认为1 #}
            function check_count(elem){
                var re = /^[1-9]\d*$/;
                if( re.test(elem.val()) === false){
                    elem.val(1)
                }
            }

            {# 全选，设置商品按钮 #}
            function check_all(elem) {
                var status = elem.prop('checked');
                $('.goods_checkbox').prop('checked', status);
            }

            {# 选择单个商品功能,设置全选按钮 #}
            function check_goods(elem) {
                if(elem.prop('checked')){
                    var selected_count = 0;
                    var length = $('.goods_checkbox').length;
                    $('.goods_checkbox').each(function () {
                        if($(this).prop('checked')){
                            selected_count +=1;
                        }
                    });
                    if(selected_count===length){
                        $('#check_all').prop('checked', true);
                    }
                }else{
                    $('#check_all').prop('checked', false);
                }
            }

            {# 删除购物车商品时维护商品总数 #}
            function calculate_totle_count(){
                {# 踩坑啦：$('.class').text()的结果是全部匹配元素字符内容加和成的新字符串 #}
                {#var count = $.cookie('count', {path: '/'});#}
                var count = $.cookie('count');
                count = parseInt(count)-1;
                $.cookie('count', count, {path: '/'});
                $('.totle_goods_count').text(count);
            }

            {# 维护购物车被勾选的商品数量、结算按钮状态 #}
            function calculate_selected_count(elem){
                var selected_count = 0;
                var length = $('.goods_checkbox').length;
                $('.goods_checkbox').each(function () {
                    if($(this).prop('checked')){
                        selected_count +=1;
                    }
                });
                $('#selected_goods_count').text(selected_count);
                if(selected_count>0){
                    $('#to_pay').attr('href', '{% url 'df_order:place_order' %}');
                    $('#to_pay').css('background-color', '#ff3d3d');
                }else{
                    $('#to_pay').attr('href', 'javascript:;');
                    $('#to_pay').css({'background-color': '#888'});
                }

            }

            {# 更新数据库中购物车里某种商品的数量 #}
            function update_sql_count(elem){
                var goods_id = elem.parents('.cart_list_td').attr('id');
                var count = elem.val();
                {# 踩坑：使用标签反向解析，会设计replace替换，有一个参数时没有问题 #}
                {# 但是有两个数字参数时，会发生前一个数字替换后的内容，再被第二个数字替换时被误替换,所以建议使用原始url #}
                {#url = '{% url 'df_cart:cart_edit' 1 2 %}'.replace('1', goods_id).replace('1', count)#}
                var url = '/df_cart/cart_edit_count/'+goods_id+'/'+count+'/';
                $.get(url);
            }

            {# 更新数据库购物车中商品是否被勾选,并回调函数更新页面数量、结算按钮状态#}
            function update_sql_status(elem){
                {# 构造ajax的url #}
                if(elem.attr('id')==='check_all'){
                    if(elem.prop('checked')){
                        var url = '/df_cart/cart_edit_status/00/1';
                    }else{
                        var url = '/df_cart/cart_edit_status/00/0';
                    }
                }else{
                    var goods_id = elem.parents('.cart_list_td').attr('id');
                    if(elem.prop('checked')){
                        var is_selected = '1';
                    }else{
                        var is_selected = '0';
                    }
                    var url = '/df_cart/cart_edit_status/'+goods_id+'/'+is_selected+'/';
                }
                $.get(url, function (data) {
                    if(data.is_succeed){
                        {# 重新计算选择的商品数量、总价 #}
                        calculate_totle();
                        calculate_selected_count();
                    }
                });
            }
            {% comment %}
            {# 更新数据库中购物车里某种商品是否被选中,**使用get传参数** #}
            function update_sql_status(elem){
                var url = '{% url 'df_cart:cart_edit_status' %}';
                if(elem.attr('id')==='check_all'){
                    if(elem.prop('checked')){
                        var data = {'check_all': true, 'status': true}
                    }else{
                        var data = {'check_all': true, 'status': false}
                    }
                    {#$.get(url, data);#}

                }else{
                    var goods_id = elem.parents('.cart_list_td').attr('id');
                    if(elem.prop('checked')){
                        var data = {'check_all': false, 'goods_id': goods_id, 'status': true}
                    }else{
                        var data = {'check_all': false, 'goods_id': goods_id, 'status': false}
                    }
                    {#$.get(url, data);#}
                }
                $.get(url, data, function (data) {

                });
            }
            {% endcomment %}

            {# 删除商品 #}
            function delete_goods(elem){
                elem.remove();
                {# 重新计算选择的商品数量、总价 #}
                calculate_totle_count();
                calculate_selected_count();
                calculate_totle();
            }

            {# 加载页面时自动调用该匿名函数，判断商品是否都被勾选，以设置全选按钮状态 #}
            !function () {
                if($(':checkbox').length > 1 && $(':checked').length+1 === $(':checkbox').length){
                    $('#check_all').prop('checked', true);
                }
            }();


            calculate_totle();
            calculate_selected_count();

            {# 加号按钮绑定click事件 #}
            $('.add').click(function () {
                {# 调用方法 #}
                add($(this));
                {# 模拟输入框失去焦点，触发相应事件 #}
                $(this).prev().blur();
            });

            {# 减号按钮绑定click事件 #}
            $('.minus').click(function () {
                {# 调用minus方法 #}
                minus($(this));
                {# 模拟输入框失去焦点，触发相应事件 #}
                $(this).next().blur();
            });

            {# input框绑定失去焦点事件 #}
            $('.num_show').blur(function () {
                {# 检验输入内容是否为大于0的数字 #}
                check_count($(this));
                {# 更新数据库#}
                update_sql_count($(this));
                {# 调用函数 #}
                calculate_totle();
            });

            {# 全选、全取消功能 #}
            $('#check_all').click(function () {
                check_all($(this));
                {# 维护商品被选状态,更新商品数量、总价 #}
                update_sql_status($(this));
            });

            {# 选择,重新计算选择商品数量、总价 #}
            $('.goods_checkbox').click(function () {
                check_goods($(this));
                {# 维护商品被选状态 #}
                update_sql_status($(this));
            });

            {# 删除购物车商品 #}
            $('.col08').click(function () {
                var goods_id = $(this).parents('.cart_list_td').attr('id');
                var url = '{% url 'df_cart:cart_delete' 1 %}'.replace('1', goods_id);
                {# 发送jquery请求，并执行回调函数 #}
                $.get(url, function (data) {
                    if(data.is_delete){
                        {# 需要删除的商品div向上收起后，执行回调函数 #}
                        $('#'+goods_id).slideUp(function(){
                            {# 在回调函数内，$(this)就指回调函数执行者 #}
                            delete_goods($(this));
                        });
                    }
                });
            });
        });

    </script>
{% endblock head %}


{% block center %}

    <div class="total_count">全部商品<em class="totle_goods_count">{{ length }}</em>件</div>
    {# 商品列表表头 #}
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>

    {% for cart in cart_list %}

        {# 购物车商品列表 #}
        <ul class="cart_list_td clearfix" id="{{ cart.goods_id }}">
            <li class="col01"><input type="checkbox" class="goods_checkbox" {% if cart.is_selected %} checked {% endif %}></li>
            <li class="col02">
                <a href="{% url 'df_goods:detail' cart.goods_id %}">
                    <img src="/static/media/{{ cart.goods.gpic }}">
                </a>
            </li>
            <li class="col03">
                <a href="{% url 'df_goods:detail' cart.goods_id %}">{{ cart.goods.gtitle }}</a><br>
                <em>{{ cart.goods.gprice }}</em>元/{{ cart.goods.gunit }}
            </li>
            <li class="col04">{{ cart.goods.gunit }}</li>
            <li class="col05"><em>{{ cart.goods.gprice }}</em>元</li>
            <li class="col06">
                <div class="num_add">
                    <a href="javascript:;" class="minus fl">-</a>
                    <input type="text" class="num_show fl" value="{{ cart.count }}">
                    <a href="javascript:;" class="add fl">+</a>
                </div>
            </li>
            <li class="col07 subtotle"> </li>
            <li class="col08"><a href="javascript:;">删除</a></li>
        </ul>
    {% endfor %}

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="is_checked" id="check_all"></li>
		<li class="col02">全选</li>
		<li class="col03">
            合计(不含运费)：<span>¥</span><em id="totle"></em><br>
            共计<b id="selected_goods_count"></b>件商品
        </li>
		<li class="col04">
            <a href="{% url 'df_order:place_order' %}" id="to_pay">去结算</a>
        </li>
	</ul>

{% endblock center %}